name: Tests

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOPROXY: "https://proxy.golang.org,direct"
      PALM_API_KEY: ${{ secrets.PALM_API_KEY }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run tests
        run: |
          go test -v ./...
